<?php

namespace frontend\controllers;

use backend\components\Data;
use Yii;
use yii\web\Controller;
use \yii\web\Response;

/**
 * Site controller
 */
class AjaxController extends Controller
{

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionGetCityByRegion()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $post = Yii::$app->request->post();
            if (!empty($post)) {
                return Data::GetCityByRegion()[$post['id']];
            }
        }
    }
    public function actionGetCommunity()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $post = Yii::$app->request->post();
            if (!empty($post)) {
                return Data::GetCommunity()[$post['id']];
            }
        }
    }
}
