<?php

namespace frontend\controllers;

use backend\components\Helper;
use common\models\LessonGropuRel;
use common\models\LessonsGroup;
use common\models\UserTestsState;
use Yii;
use yii\web\Controller;


/**
 * Site controller
 */
class LessonsController extends Controller
{

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout = 'profile';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {


        $LessonsGroup = LessonsGroup::CurrentId();

        $user_tests_state = UserTestsState::GetCurrentUserState();
        if (empty($user_tests_state)) {
            UserTestsState::SaveFirstUserTestState();
            $user_tests_state = UserTestsState::GetCurrentUserState();
        }

//        Helper::out(LessonGropuRel::GetAllById($LessonsGroup['id']));
//        exit;
        return $this->render('index', [
            'lessons_group' => LessonGropuRel::GetAllById($LessonsGroup['id']),
            'lessons_global' => $LessonsGroup,
            'user_tests_state' => $user_tests_state,
            'done_count' => count(UserTestsState::GetCurrentUserStateByDone())
        ]);
    }


}
