<?php
namespace frontend\controllers;

use backend\components\Helper;
use common\models\LessonGropuRel;
use common\models\LessonsGroup;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class LessonsController extends Controller
{

    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
           return  $this->goHome();
        }
        $this->layout = 'profile';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $LessonsGroup = LessonsGroup::CurrentId();
        return $this->render('index',[
            'lessons_group' =>LessonGropuRel::GetAllById($LessonsGroup['id'])
        ]);
    }


}
