<?php

namespace frontend\controllers;

use backend\components\Data;
use backend\components\Helper;
use common\models\User;
use common\models\UserTestsState;
use frontend\models\SignupForm;
use Yii;
use yii\web\Controller;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class ProfileController extends Controller
{

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout = 'profile';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {

        if (Yii::$app->request->post('User')) {
            User::SaveUserData(Yii::$app->request->post('User'));
        }
        $model = User::findIdentity(Yii::$app->user->getId());
        return $this->render('index', [
            'model' => $model,
        ]);
    }

    public function actionDrag()
    {
//        $this->layout = false;
        return $this->render('drag', [

        ]);
    }

    public function actionChoose()
    {
        $this->layout = false;
        return $this->render('choose', [

        ]);
    }

    public function actionChoose2()
    {
        $this->layout = false;
        return $this->render('choose_2', [

        ]);
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                exit;
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionFaq()
    {
        return $this->render('faq');
    }

    public function actionChange()
    {
        return $this->render('change', [
            'class_8' => [
                'link' => '/profile/change-grade?g=8',
                'class' => Yii::$app->user->identity->current_grade == 8 ? 'active-choose' : ''
            ],
            'class_9' => [
                'link' => (Yii::$app->user->identity->grade >= 9 || UserTestsState::CheckUserLesson(8)) ? '/profile/change-grade?g=9' : '#',
                'class' => Yii::$app->user->identity->current_grade == 9 ? 'active-choose' : '',
                'class1' => (9 < Yii::$app->user->identity->grade || UserTestsState::CheckUserLesson(8)) ? '' : 'inactive-choose'
            ],
            'class_10' => [
                'link' => (Yii::$app->user->identity->grade >= 10 || UserTestsState::CheckUserLesson(9)) ? '/profile/change-grade?g=10' : '#',
                'class' => Yii::$app->user->identity->current_grade == 10 ? 'active-choose' : '',
                'class1' => (10 < Yii::$app->user->identity->grade || UserTestsState::CheckUserLesson(9)) ? '' : 'inactive-choose'
            ],
            'class_11' => [
                'link' => (Yii::$app->user->identity->grade >= 11 || UserTestsState::CheckUserLesson(10)) ? '/profile/change-grade?g=11' : '#',
                'class' => Yii::$app->user->identity->current_grade == 11 ? 'active-choose' : '',
                'class1' => (11 < Yii::$app->user->identity->grade || UserTestsState::CheckUserLesson(10)) ? '' : 'inactive-choose'
            ],
        ]);
    }

    public function actionChangeGrade($g)
    {
        if (Yii::$app->user->identity->grade >= $g || UserTestsState::CheckUserLesson($g - 1)) {
            User::UpdateGrade($g);
        }
        return $this->redirect('/lessons');
    }

    public function actionCertificates()
    {
        return $this->render('certificates', []);
    }
}
